import type { Category, Offer, OfferImage, OfferArticleNumber } from '@/types/database';

export const sampleCategories: Category[] = [
  { id: 'cat-1', name_de: 'Lebensmittel', name_en: 'Food', name_ru: 'Продукты', slug: 'food', sort_order: 1, created_at: '2024-01-01' },
  { id: 'cat-2', name_de: 'Getränke', name_en: 'Beverages', name_ru: 'Напитки', slug: 'beverages', sort_order: 2, created_at: '2024-01-01' },
  { id: 'cat-3', name_de: 'Süßwaren', name_en: 'Confectionery', name_ru: 'Кондитерские изделия', slug: 'confectionery', sort_order: 3, created_at: '2024-01-01' },
  { id: 'cat-4', name_de: 'Drogerie', name_en: 'Drugstore', name_ru: 'Бытовая химия', slug: 'drugstore', sort_order: 4, created_at: '2024-01-01' },
  { id: 'cat-5', name_de: 'Haushalt', name_en: 'Household', name_ru: 'Товары для дома', slug: 'household', sort_order: 5, created_at: '2024-01-01' },
  { id: 'cat-6', name_de: 'Tierbedarf', name_en: 'Pet Supplies', name_ru: 'Товары для животных', slug: 'pet-supplies', sort_order: 6, created_at: '2024-01-01' },
  { id: 'cat-7', name_de: 'Non-Food', name_en: 'Non-Food', name_ru: 'Непродовольственные товары', slug: 'non-food', sort_order: 7, created_at: '2024-01-01' },
];

export const sampleOffers: (Offer & { category?: Category; images?: OfferImage[]; article_numbers?: OfferArticleNumber[] })[] = [
  {
    id: 'offer-1',
    title: 'Barilla Spaghetti No.5 500g',
    brand: 'Barilla',
    short_description: 'Klassische italienische Spaghetti, MHD 06/2025',
    long_description: 'Barilla Spaghetti No.5 in 500g Packungen. Mindesthaltbarkeitsdatum Juni 2025. Originalverpackt, keine Beschädigungen. Ideal für den Einzelhandel oder Gastronomie.',
    quantity_total: 5000,
    quantity_available: 5000,
    unit: 'Stück',
    volume_text: '500g pro Packung',
    price_per_unit: 0.89,
    currency: 'EUR',
    condition_code: 'A',
    category_id: 'cat-1',
    export_only: false,
    public_visible: true,
    min_price_internal: 0.65,
    in_stock: true,
    status: 'active',
    created_by: 'admin-1',
    created_at: '2024-03-01',
    updated_at: '2024-03-01',
    category: sampleCategories[0],
    images: [{ id: 'img-1', offer_id: 'offer-1', url: '', sort_order: 0, created_at: '2024-03-01' }],
    article_numbers: [{ id: 'an-1', offer_id: 'offer-1', article_number: '8076809513456' }],
  },
  {
    id: 'offer-2',
    title: 'Red Bull Energy Drink 250ml',
    brand: 'Red Bull',
    short_description: 'Red Bull Classic Dosen, 24er Tray',
    long_description: 'Red Bull Energy Drink in 250ml Dosen. 24 Stück pro Tray. MHD mindestens 3 Monate. Leichte Verpackungsschäden am Tray, Dosen einwandfrei.',
    quantity_total: 800,
    quantity_available: 600,
    unit: 'Stück',
    volume_text: '250ml pro Dose, 24er Tray',
    price_per_unit: 0.75,
    currency: 'EUR',
    condition_code: 'B',
    category_id: 'cat-2',
    export_only: false,
    public_visible: true,
    min_price_internal: 0.55,
    in_stock: true,
    status: 'partially_sold',
    created_by: 'admin-1',
    created_at: '2024-03-02',
    updated_at: '2024-03-05',
    category: sampleCategories[1],
    images: [{ id: 'img-2', offer_id: 'offer-2', url: '', sort_order: 0, created_at: '2024-03-02' }],
    article_numbers: [{ id: 'an-2', offer_id: 'offer-2', article_number: '9002490100070' }],
  },
  {
    id: 'offer-3',
    title: 'Milka Alpenmilch Schokolade 100g',
    brand: 'Milka',
    short_description: 'Milka Alpenmilch Tafelschokolade, MHD 09/2025',
    long_description: 'Milka Alpenmilch Schokolade 100g Tafeln. Mindesthaltbarkeitsdatum September 2025. Originalverpackt. Kartonweise verfügbar (24 Stück pro Karton).',
    quantity_total: 10000,
    quantity_available: 10000,
    unit: 'Stück',
    volume_text: '100g pro Tafel',
    price_per_unit: 0.59,
    currency: 'EUR',
    condition_code: 'A',
    category_id: 'cat-3',
    export_only: false,
    public_visible: true,
    min_price_internal: 0.42,
    in_stock: true,
    status: 'active',
    created_by: 'admin-1',
    created_at: '2024-03-03',
    updated_at: '2024-03-03',
    category: sampleCategories[2],
    images: [{ id: 'img-3', offer_id: 'offer-3', url: '', sort_order: 0, created_at: '2024-03-03' }],
    article_numbers: [
      { id: 'an-3', offer_id: 'offer-3', article_number: '7622210078100' },
      { id: 'an-3b', offer_id: 'offer-3', article_number: '7622210078117' },
    ],
  },
  {
    id: 'offer-4',
    title: 'Persil Universal Megaperls 23WL',
    brand: 'Persil',
    short_description: 'Persil Universal Waschmittel Megaperls',
    long_description: 'Persil Universal Megaperls für 23 Waschladungen. Originalverpackt. Leicht beschädigte Verpackung, Inhalt einwandfrei. Nur für Export bestimmt.',
    quantity_total: 2000,
    quantity_available: 2000,
    unit: 'Stück',
    volume_text: '23 Waschladungen',
    price_per_unit: 3.49,
    currency: 'EUR',
    condition_code: 'B',
    category_id: 'cat-4',
    export_only: true,
    public_visible: true,
    min_price_internal: 2.80,
    in_stock: true,
    status: 'active',
    created_by: 'admin-1',
    created_at: '2024-03-04',
    updated_at: '2024-03-04',
    category: sampleCategories[3],
    images: [{ id: 'img-4', offer_id: 'offer-4', url: '', sort_order: 0, created_at: '2024-03-04' }],
    article_numbers: [{ id: 'an-4', offer_id: 'offer-4', article_number: '4015200031060' }],
  },
  {
    id: 'offer-5',
    title: 'Pedigree Vital Adult Rind 15kg',
    brand: 'Pedigree',
    short_description: 'Trockenfutter für Hunde, Geschmacksrichtung Rind',
    long_description: 'Pedigree Vital Protection Adult Trockenfutter mit Rind, 15kg Sack. MHD Januar 2026. Palettenverfügbar.',
    quantity_total: 120,
    quantity_available: 120,
    unit: 'Palette',
    volume_text: '15kg pro Sack, 33 Säcke pro Palette',
    price_per_unit: 450,
    currency: 'EUR',
    condition_code: 'A',
    category_id: 'cat-6',
    export_only: false,
    public_visible: true,
    min_price_internal: 380,
    in_stock: true,
    status: 'active',
    created_by: 'admin-1',
    created_at: '2024-03-05',
    updated_at: '2024-03-05',
    category: sampleCategories[5],
    images: [{ id: 'img-5', offer_id: 'offer-5', url: '', sort_order: 0, created_at: '2024-03-05' }],
    article_numbers: [{ id: 'an-5', offer_id: 'offer-5', article_number: '5998749108741' }],
  },
  {
    id: 'offer-6',
    title: 'Mischposten Haushaltsartikel',
    brand: 'Diverse',
    short_description: 'Gemischter Posten Haushaltsartikel verschiedener Marken',
    long_description: 'Mischposten bestehend aus Küchenutensilien, Aufbewahrungsboxen und Reinigungsartikeln. Verschiedene Marken (Leifheit, Emsa, Vileda). Teils beschädigte Verpackung.',
    quantity_total: 1,
    quantity_available: 1,
    unit: 'Posten',
    volume_text: 'ca. 500 Teile gemischt',
    price_per_unit: 2500,
    currency: 'EUR',
    condition_code: 'C',
    category_id: 'cat-5',
    export_only: false,
    public_visible: true,
    min_price_internal: 1800,
    in_stock: true,
    status: 'active',
    created_by: 'admin-1',
    created_at: '2024-03-06',
    updated_at: '2024-03-06',
    category: sampleCategories[4],
    images: [{ id: 'img-6', offer_id: 'offer-6', url: '', sort_order: 0, created_at: '2024-03-06' }],
    article_numbers: [],
  },
];

export const sampleShareLink = {
  id: 'sl-1',
  token: 'demo',
  manager_id: 'mgr-1',
  label: 'Demo Katalog',
  filters: {},
  default_language: 'de' as const,
  active: true,
  created_at: '2024-03-01',
};

export const sampleManager = {
  id: 'mgr-1',
  user_id: 'user-1',
  display_name: 'Max Mustermann',
  whatsapp_number: '+491234567890',
  default_language: 'de' as const,
  created_at: '2024-01-01',
};
